# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_EdgeDetection_0_0/imageProcessingSystem_EdgeDetection_0_0.xci
# IP: The module: 'imageProcessingSystem_EdgeDetection_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_EdgeDetection_0_0/imageProcessingSystem_EdgeDetection_0_0.xci
# IP: The module: 'imageProcessingSystem_EdgeDetection_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
