# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_processing_system7_0_0/imageProcessingSystem_processing_system7_0_0.xci
# IP: The module: 'imageProcessingSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_processing_system7_0_0/imageProcessingSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_processing_system7_0_0/imageProcessingSystem_processing_system7_0_0.xci
# IP: The module: 'imageProcessingSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_processing_system7_0_0/imageProcessingSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
