# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_auto_pc_0/imageProcessingSystem_auto_pc_0.xci
# IP: The module: 'imageProcessingSystem_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_auto_pc_0/imageProcessingSystem_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_auto_pc_0/imageProcessingSystem_auto_pc_0.xci
# IP: The module: 'imageProcessingSystem_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/viv_wd/Edge_d_IPS/Edge_d_IPS.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_auto_pc_0/imageProcessingSystem_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
