# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir V:/viv_wd/Edge_detection/Edge_detection.cache/wt [current_project]
set_property parent.project_path V:/viv_wd/Edge_detection/Edge_detection.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths {
  v:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/imports/imageprocessing
  v:/viv_wd/imageprocessing
} [current_project]
set_property ip_output_repo v:/viv_wd/Edge_detection/Edge_detection.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  V:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/new/conv.v
  V:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/new/imageControl.v
  V:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/new/lineBuffer.v
  V:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/new/imageProcessTop.v
}
read_ip -quiet V:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
set_property used_in_implementation false [get_files -all v:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc]
set_property used_in_implementation false [get_files -all v:/viv_wd/Edge_detection/Edge_detection.srcs/sources_1/ip/outputBuffer/outputBuffer_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top imageProcessTop -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef imageProcessTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file imageProcessTop_utilization_synth.rpt -pb imageProcessTop_utilization_synth.pb"
