# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/imageProcessingSystem_axi_smc_0.xci
# IP: The module: 'imageProcessingSystem_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/bd_a676.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_10/bd_a676_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_16/bd_a676_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_20/bd_a676_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_26/bd_a676_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_21/bd_a676_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_22/bd_a676_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_23/bd_a676_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_24/bd_a676_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_25/bd_a676_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_17/bd_a676_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_18/bd_a676_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_19/bd_a676_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_13/bd_a676_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_14/bd_a676_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_15/bd_a676_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_11/bd_a676_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_12/bd_a676_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_7/bd_a676_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_8/bd_a676_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_9/bd_a676_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_2/bd_a676_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_3/bd_a676_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_4/bd_a676_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_5/bd_a676_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_6/bd_a676_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_0/bd_a676_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_1/bd_a676_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_10/bd_a676_s00a2s_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_16/bd_a676_s01a2s_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_20/bd_a676_m00s2a_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_21/bd_a676_m00arn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_22/bd_a676_m00rn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_23/bd_a676_m00awn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_24/bd_a676_m00wn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_25/bd_a676_m00bn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_17/bd_a676_sawn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_18/bd_a676_swn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_19/bd_a676_sbn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_11/bd_a676_sarn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_12/bd_a676_srn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_2/bd_a676_arsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_3/bd_a676_rsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_4/bd_a676_awsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_5/bd_a676_wsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_6/bd_a676_bsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_1/bd_a676_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_1/bd_a676_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/imageProcessingSystem_axi_smc_0.xci
# IP: The module: 'imageProcessingSystem_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/bd_a676.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_10/bd_a676_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_16/bd_a676_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_20/bd_a676_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_26/bd_a676_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_21/bd_a676_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_22/bd_a676_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_23/bd_a676_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_24/bd_a676_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_25/bd_a676_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_17/bd_a676_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_18/bd_a676_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_19/bd_a676_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_13/bd_a676_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_14/bd_a676_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_15/bd_a676_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_11/bd_a676_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_12/bd_a676_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_7/bd_a676_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_8/bd_a676_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_9/bd_a676_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_2/bd_a676_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_3/bd_a676_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_4/bd_a676_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_5/bd_a676_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_6/bd_a676_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_0/bd_a676_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_1/bd_a676_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_10/bd_a676_s00a2s_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_16/bd_a676_s01a2s_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_20/bd_a676_m00s2a_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_21/bd_a676_m00arn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_22/bd_a676_m00rn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_23/bd_a676_m00awn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_24/bd_a676_m00wn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_25/bd_a676_m00bn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_17/bd_a676_sawn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_18/bd_a676_swn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_19/bd_a676_sbn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_11/bd_a676_sarn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_12/bd_a676_srn_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_2/bd_a676_arsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_3/bd_a676_rsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_4/bd_a676_awsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_5/bd_a676_wsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_6/bd_a676_bsw_0_ooc.xdc

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_1/bd_a676_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/bd_0/ip/ip_1/bd_a676_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: v:/viv_wd/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
