# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/imageProcessingSystem/imageProcessingSystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem || ORIG_REF_NAME==imageProcessingSystem} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_processing_system7_0_0/imageProcessingSystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_processing_system7_0_0 || ORIG_REF_NAME==imageProcessingSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_0/imageProcessingSystem_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_axi_dma_0_0 || ORIG_REF_NAME==imageProcessingSystem_axi_dma_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_ps7_0_axi_periph_0/imageProcessingSystem_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==imageProcessingSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_rst_ps7_0_100M_0/imageProcessingSystem_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_rst_ps7_0_100M_0 || ORIG_REF_NAME==imageProcessingSystem_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_axis_dwidth_converter_0_0/imageProcessingSystem_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_axis_dwidth_converter_0_0 || ORIG_REF_NAME==imageProcessingSystem_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_axi_smc_0/imageProcessingSystem_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_axi_smc_0 || ORIG_REF_NAME==imageProcessingSystem_axi_smc_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_xlconcat_0_0/imageProcessingSystem_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_xlconcat_0_0 || ORIG_REF_NAME==imageProcessingSystem_xlconcat_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_system_ila_0_0/imageProcessingSystem_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_system_ila_0_0 || ORIG_REF_NAME==imageProcessingSystem_system_ila_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_EdgeDetection_0_0/imageProcessingSystem_EdgeDetection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_EdgeDetection_0_0 || ORIG_REF_NAME==imageProcessingSystem_EdgeDetection_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_auto_pc_0/imageProcessingSystem_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_auto_pc_0 || ORIG_REF_NAME==imageProcessingSystem_auto_pc_0} -quiet] -quiet

# XDC: bd/imageProcessingSystem/imageProcessingSystem_ooc.xdc
